development:
  username: root
  adapter: mysql
  database: cairn_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: cairn_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: cairn_production
  host: localhost
  password: ''

