development:
  username: root
  adapter: mysql
  database: vanilla_development
  host: localhost
  password: ''
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
production: 
  username: root
  adapter: mysql
  database: vanilla_production
  host: localhost
  password: ''

