development:
  username: root
  adapter: mysql
  database: cairn3_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: cairn3_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: cairn3_production
  host: localhost
  password: ''

