site_name: Cairn
site_url: http://cairn.yoomee.com/
webthumb_key: ff1e5c1f36807f9e87868f9c01c33dbb
# http_basic_username: cairn
# http_basic_password: pie123
development:
  site_name: Cairn development
production:
  site_url: http://cairntechnology.com
  google_analytics: UA-27206886-1